global:
  marketplace-ami: true
  owner: quickstart-eng@amazon.com
  qsname: quickstart-informatica-bdm
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-southeast-2
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-2
  reporting: true
tests:
  master:
    parameter_input: informatica-bdm-master.json
    template_file: informatica-bdm-master.template
